In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_rows' , None)
pd.set_option('display.max_columns' , None)

import tensorflow as tf
from tf.keras import Sequential , Input
from tf.keras.layers import Dense


In [9]:
# Load the dataset.

(x_train , y_train) , (x_test,y_test) = tf.keras.datasets.mnist.load_data()

print(f"Shape of x train: {x_train.shape}\nShape of y train: {y_train.shape}\nShape of x test: {x_test.shape}\nShape of y test: {y_test.shape}")

11490434/11490434 [==============================] - 0s 0us/step
Shape of x train: (60000, 28, 28)
Shape of y train: (60000,)
Shape of x test: (10000, 28, 28)
Shape of y test: (10000,)


In [14]:
x_train.shape[1]

28

In [22]:
y_train[:100]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3, 1], dtype=uint8)

In [12]:
x_train[:1]

array([[[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           3,  18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,
           0,   0,   0

In [24]:
# Build a neural-network model.



model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128 , activation = 'relu'),
    tf.keras.layers.Dense(64 , activation = 'relu'),
    tf.keras.layers.Dense(10 , activation = 'softmax')
])

model.compile(optimizer = 'adam' , loss = 'sparse_categorical_crossentropy' , metrics = ['accuracy'])


In [26]:
model.fit(x_train , y_train , validation_data=(x_test,y_test) , epochs = 20)

Epoch 1/20
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0838 - accuracy: 0.9768 - val_loss: 0.1770 - val_accuracy: 0.9623
Epoch 2/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0801 - accuracy: 0.9785 - val_loss: 0.1466 - val_accuracy: 0.9699
Epoch 3/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0739 - accuracy: 0.9802 - val_loss: 0.2215 - val_accuracy: 0.9607
Epoch 4/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0754 - accuracy: 0.9795 - val_loss: 0.1945 - val_accuracy: 0.9636
Epoch 5/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0711 - accuracy: 0.9815 - val_loss: 0.1582 - val_accuracy: 0.9664
Epoch 6/20
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0655 - accuracy: 0.9830 - val_loss: 0.1669 - val_accuracy: 0.9704
Epoch 7/20
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0687 - accuracy: 0.9823 - val_loss: 0.1695 - val_accuracy:

In [27]:
# Model Evaluation.

model.evaluate(x_test,y_test , verbose = 2 )

313/313 - 0s - loss: 0.2087 - accuracy: 0.9712 - 333ms/epoch - 1ms/step


[0.2087297886610031, 0.9711999893188477]

In [28]:
y_pred = model.predict(x_test)

y_pred[:1]

313/313 [==============================] - 1s 2ms/step


array([[1.5121695e-19, 3.6055503e-15, 1.1561863e-10, 1.4131887e-10,
        2.1523975e-15, 1.6610176e-16, 0.0000000e+00, 9.9999994e-01,
        1.0608929e-18, 1.2129885e-10]], dtype=float32)

In [38]:
# Saving the model in hdfs [h5] mode.

filepath = 'D:\All-About-Deep-Learning\save_models'
tf.keras.saving.save_model(model ,filepath, overwrite = True , save_format = 'h5')